# 1. Numpy and Linear Algebra (선형대수)

- 수치 data 를 다루는데 효율적이고 높은 성능 제공

- 각종 수학적 함수 제공

- Python scientific library 들이 Numpy 기반으로 구축

### ndarray

- n-dimensional array (다차원 배열 객체) 로 구성 

In [2]:
import sys
import numpy as np

In [3]:
# 스칼라
x = 6
x

6

In [4]:
a = np.array([1])
a, a.shape

(array([1]), (1,))

In [5]:
# 벡터
x = np.array([1,2,3])

print("x = ", x)
print("dimension of x is {}".format(x.shape))

x =  [1 2 3]
dimension of x is (3,)


In [6]:
# matrix
y = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
print("array dimension {}".format(y.shape))
print("array size {}".format(y.size))

array dimension (3, 3)
array size 9


In [8]:
x = np.array([[[1, 2, 3], 
               [3, 2, 5]], 
              [[1, 7, 8], 
               [5, 4, 6]]])

x.shape

(2, 2, 3)

## Indexing / Slicing

<img src="numpy1.png" width="300">

In [9]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
print(arr[:2, 1:])

[[2 3]
 [5 6]]


In [11]:
arr[2]

array([7, 8, 9])

In [12]:
arr[2, :]

array([7, 8, 9])

In [13]:
arr[2:, :]

array([[7, 8, 9]])

In [14]:
print(arr[:, :2])

[[1 2]
 [4 5]
 [7 8]]


In [15]:
arr[1, :2]

array([4, 5])

In [16]:
arr[1:2, :2]

array([[4, 5]])